### ISSUE TITLE
Local Files from the same artist can't be weighted

### ISSUE THREAD

**Issue by 12CPS** [mwaterman29/spicetify-weighted-playlists#4]
I have a few playlists that use a lot of my local files. Any time that I try to weigh the song, the weight is set for every one of that artist's songs. 
![image](https://user-images.githubusercontent.com/70449322/227807679-b4b34acd-3a7b-445a-a714-7dd0efd0b5b6.png)

As you can see, the weight can be set for the first song from each artist. However, the second song will only show [Weight] and will take on the same weighting as the first song. In the example below, the songs by Alicia Keys, Desiigner, and Future are all working properly and can be weighted. The first Kanye West song can be weighted, but every following songs can not. 
![image](https://user-images.githubusercontent.com/70449322/227807908-2cdd825b-eb10-4ce8-ab71-cc1f7046cd68.png)

**Comment by mwaterman29** [comment]
Hi, sorry about that, I had stepped away from this project for a bit due to working full-time on top of being a student.

Now that I'm done with school, I'll be back to maintaining this.

I'm not 100% sure how local files are handled by Spotify - this could be an issue to due that, or it could be out of date. I'm much better with Typescript and React now, thanks to my experience at work, so I'll be cleaning up the whole extension and ensuring it's up to date for this version.

If I can resolve this, I will. Either way, expect an update within a week or two :)

**Comment by mwaterman29** [comment]
I've looked into this, and it seems like the extension is mostly incompatible with how Spotify handles local files. I'll look into this again in the future, but I have a few other priority projects right now, sorry.
It should be possible in the future, but it'll be at least a little bit before I get back to it.
